### ISSUE TITLE
magentatv.at.ini: unhandled exception

### ISSUE THREAD

**Issue by forenta** [SilentButeo2/webgrabplus-siteinipack#554]
https://github.com/SilentButeo2/webgrabplus-siteinipack/blob/d7741f764281cf830fa4feae0e00c58335ed816c/siteini.pack/Austria/magentatv.at.ini

Seems to be broken, this is how it crashes:

```
[  Info  ] (  37/76  ) MAGENTATV.AT -- chan. (xmltv_id=krone.tv HD) -- mode Incremental
[        ] Job finished at 19/04/2023 19:49:18 done in 7m 38s
[Critical] 
One or more errors occurred. (Invalid URI: The hostname could not be parsed.)
[Critical] 
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at  .‧. (String ,   )
   at  .․. (String[] )
[Critical] Unhandled Exception
[Critical] For detailed info, see log file C:\Users\user\AppData\Local\WebGrab+Plus\WebGrab++.log.txt
[Critical] Execution stopped
```

**Comment by Pancronos** [comment]
Please use forum for this issues
